from .animals import Animal
from .beaver import Beaver
from .cat import Cat
from .dog import Dog
from .donkey import Donkey
from .duck import Duck
from .eel import Eel
from .fish import Fish
from .frog import Frog
from .goat import Goat
from .iguana import Iguana
from .llama import Llama
from .scorpion import Scorpion
from .snake import Snake
from .tarantula import Tarantula
from .turtle import Turtle